// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskOrganizer.Data;

#nullable disable

namespace TaskOrganizer.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824093205_AjoutRappels")]
    partial class AjoutRappels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("CategorieTache", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TachesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoriesId", "TachesId");

                    b.HasIndex("TachesId");

                    b.ToTable("TacheCategories", (string)null);
                });

            modelBuilder.Entity("TaskOrganizer.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("TaskOrganizer.Models.Rappel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateHeureRappel")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Declenche")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Offset")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TacheId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TacheId");

                    b.HasIndex("Declenche", "DateHeureRappel");

                    b.ToTable("Rappels", (string)null);
                });

            modelBuilder.Entity("TaskOrganizer.Models.Tache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateEcheance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Priorite")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Taches", (string)null);
                });

            modelBuilder.Entity("CategorieTache", b =>
                {
                    b.HasOne("TaskOrganizer.Models.Categorie", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskOrganizer.Models.Tache", null)
                        .WithMany()
                        .HasForeignKey("TachesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskOrganizer.Models.Rappel", b =>
                {
                    b.HasOne("TaskOrganizer.Models.Tache", "Tache")
                        .WithMany("Rappels")
                        .HasForeignKey("TacheId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tache");
                });

            modelBuilder.Entity("TaskOrganizer.Models.Tache", b =>
                {
                    b.Navigation("Rappels");
                });
#pragma warning restore 612, 618
        }
    }
}
